# Generated by Django 3.0.5 on 2020-04-09 11:20

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
    
    ]
