# Generated by Django 3.0.5 on 2020-04-15 22:23

from django.db import migrations, models

def create_data(apps, schema_editor):
    Student = apps.get_model('students', 'Student')
    Student(first_name="Buffy", last_name="Summers", 
    email="bsummers@ucsunnydale.edu", phone="6507571113", address="202 Collier St", address_two= "#23", city="Sunnydale", state="CA", zip_code="97411", bio= "Average Student").save()

class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address_two',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='student',
            name='state',
            field=models.CharField(max_length=30, null=True, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='student',
            name='zip_code',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.RunPython(create_data),
    ]
